# Generated by Django 5.1.3 on 2024-11-24 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('company_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance')], max_length=20)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('required_experience', models.CharField(blank=True, max_length=50, null=True)),
                ('skills_required', models.TextField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('posted_by', models.ForeignKey(limit_choices_to={'user_role': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
