# Generated by Django 5.1.3 on 2024-12-14 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companymodel_employees'),
        ('jobs', '0002_jobmodel_job_level_jobmodel_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='company_name',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='company.companymodel'),
        ),
    ]
