# Generated by Django 5.1.3 on 2024-12-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobmodel_applicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('fresher', 'Fresher'), ('temporary', 'Temporary')], max_length=20),
        ),
    ]
