# Generated by Django 5.1.3 on 2024-12-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobmodel_negotiable_alter_jobmodel_job_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='salary_range',
            new_name='salary',
        ),
    ]
