# Generated by Django 5.1.3 on 2024-12-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_rename_salary_range_jobmodel_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='negotiable',
        ),
    ]
