# Generated by Django 5.1.3 on 2024-12-14 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companymodel_employees'),
        ('jobs', '0007_remove_jobmodel_negotiable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='company.companymodel'),
        ),
    ]
