# Generated by Django 5.1.3 on 2024-12-14 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_jobmodel_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
