# Generated by Django 5.1.3 on 2024-12-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_jobslikedmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='applicants',
        ),
    ]
