# Generated by Django 5.1.3 on 2024-11-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('job_role', models.CharField(blank=True, choices=[('software_engineer', 'Software Engineer'), ('frontend_developer', 'Frontend Developer'), ('qa_engineer', 'QA Engineer'), ('back_end_developer', 'Backend Developer'), ('project_manager', 'Project Manager'), ('full_stack_developer', 'Full Stack Developer'), ('uiux_designer', 'UI/UX Designer'), ('graphics_designer', 'Graphics Designer'), ('laravel_developer', 'Laravel Developer'), ('digital_marketing', 'Digital Marketing'), ('php_developer', 'PHP Developer'), ('flutter_developer', 'Flutter Developer')], max_length=100, null=True)),
                ('user_role', models.CharField(choices=[('admin', 'admin'), ('seeker', 'seeker'), ('provider', 'provider')], default='seeker', max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('cv', models.FileField(blank=True, default=None, null=True, upload_to='cv')),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
