# Generated by Django 5.1.3 on 2024-12-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_images'),
        ),
    ]
