# Generated by Django 5.1.3 on 2024-12-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel_experience_alter_usermodel_job_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
