# Generated by Django 5.1.3 on 2024-12-13 16:20

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermodel_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='cv',
            field=models.FileField(blank=True, default=None, null=True, upload_to=apps.users.models.cv_upload_path),
        ),
    ]
