# Generated by Django 5.1.3 on 2024-12-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobmodel_job_level_jobmodel_shift'),
        ('users', '0004_alter_usermodel_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='liked_jobs',
            field=models.ManyToManyField(related_name='liked_jobs', to='jobs.jobmodel'),
        ),
    ]
