# Generated by Django 5.1.3 on 2024-12-14 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companymodel_employees'),
        ('jobs', '0003_remove_jobmodel_company_name_jobmodel_company'),
        ('users', '0006_usermodel_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='company.companymodel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='liked_jobs',
            field=models.ManyToManyField(null=True, related_name='liked_jobs', to='jobs.jobmodel'),
        ),
    ]
