# Generated by Django 5.1.3 on 2024-12-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobmodel_company_name_jobmodel_company'),
        ('users', '0007_alter_usermodel_company_alter_usermodel_liked_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='liked_jobs',
            field=models.ManyToManyField(blank=True, related_name='liked_jobs', to='jobs.jobmodel'),
        ),
    ]
