# Generated by Django 5.1.3 on 2024-12-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usermodel_liked_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='liked_jobs',
        ),
    ]
