# Generated by Django 5.1.3 on 2024-12-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_companymodel_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
