# Generated by Django 5.1.3 on 2024-12-22 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='applicant',
            field=models.ForeignKey(limit_choices_to={'user_role': 'seeker'}, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobmodel'),
        ),
        migrations.AddConstraint(
            model_name='applicationmodel',
            constraint=models.UniqueConstraint(fields=('job', 'applicant'), name='unique_application_per_job'),
        ),
    ]
