# Generated by Django 5.1.3 on 2024-12-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmodel',
            name='applicant',
        ),
    ]
