# Generated by Django 5.1.3 on 2024-12-24 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='applicant',
            field=models.ForeignKey(limit_choices_to={'user_role': 'seeker'}, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to=settings.AUTH_USER_MODEL),
        ),
    ]
